version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  release:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-path: ~/project/node_modules
          include-branch-in-cache-key: false
      - run: node ./scripts/build.js  
      - run: yarn workspaces run semantic-release

workflows:
  release:
    jobs:
      - release